### PR TITLE
Loosen gemspec, allow usage with rails 5 

### LINKED ISSUE #112: (Rails 5) 0.2.6 causes bundle conflict due to activesupport < 5.0 dependency
I'm unable to update the gem `5.2.6` version due to this line in the gemspec:

`s.add_runtime_dependency 'activesupport', '< 5.0', '>= 3.0'`

This seems to have been changed between commits bb6c7ba6f4e574b268a460ef7909aa5021248e1a and
9deae35f5809d33e7b1f5c47264a22ad63f7f158

Using `rails 5.0.0.1` on `bundle update`, I'm getting this error:

```
airborne (= 0.2.6) was resolved to 0.2.6, which depends on
      activesupport (< 5.0, >= 3.0)
```

### PR DESCRIPTION
**Pull request by rosskevin**
Fixes #112

### CODE REVIEW

**Comment by adisos** [comment]
@brooklynDev 

Please review this PR. Thanks in advance.

**Comment by kesha-antonov** [comment]
@brooklynDev +1

**Comment by hcarreras** [comment]
This does not fix the dependency issue for me:

```
    rspec-rails (~> 3.5) was resolved to 3.5.2, which depends on
      actionpack (>= 3.0) was resolved to 5.0.1, which depends on
        rack (~> 2.0)

    airborne was resolved to 0.2.7, which depends on
      rack (< 2.0)

    rspec-rails (~> 3.5) was resolved to 3.5.2, which depends on
      actionpack (>= 3.0) was resolved to 5.0.1, which depends on
        rack-test (~> 0.6.3) was resolved to 0.6.3, which depends on
          rack (>= 1.0)

    rails (~> 5.0.1) was resolved to 5.0.1, which depends on
      sprockets-rails (>= 2.0.0) was resolved to 3.2.0, which depends on
        sprockets (>= 3.0.0) was resolved to 3.7.1, which depends on
          rack (< 3, > 1)


```

**Comment by rosskevin** [comment]
@hcarreras - this is not the constraint for your problem then, you need to examine your lock file for other constraining gems and trace their sources. As-is, this PR works with rails 5.

**Comment by hcarreras** [comment]
@rosskevin you are right. I've finally made it work. Sorry for the confusion.

**Comment by dim** [comment]
:+1:

**Comment by gee-forr** [comment]
Hey @brooklynDev - will this PR get merged soon? I ask, for 2 reasons, 1) because I'd like to start pulling this gem from rubygems.org again, and 2) I'd like to issue a PR for #126, but would prefer to base it off an accepted version of @rosskevin's changes.

**Comment by sethpollack** [comment]
Thanks!

**Pull request merged**
