### PR TITLE
Remove duplicate word and newline in error message

### PR DESCRIPTION
**Pull request by alcesleo**

### CODE REVIEW

**Comment by sethpollack** [comment]
Thanks @alcesleo! Can you fix the failing tests? Also please leave the newline in.

**Comment by alcesleo** [comment]
Sure thing, just edited it on github, it looks like the other similar messages do not have a newline though, what is the purpose of it?

**Comment by sethpollack** [comment]
I was trying to keep consistent with rspec. They use this format `"\nexpected: #{expected_formatted}\n     got: #{actual_formatted}\n\n(compared using eql?)\n"`

We should probably add the `expected:` and `got:` to our messages.

**Comment by alcesleo** [comment]
I force pushed my branch to do what you asked :)

**Comment by sethpollack** [comment]
Ok thanks!

**Pull request merged**
